// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-BnpsVALvjI4BukLmqG09D7lTyftJA0k',
    appId: '1:1002546867181:web:4ab383fbc3b051d49c95e4',
    messagingSenderId: '1002546867181',
    projectId: 'tiktokclone-f6937',
    authDomain: 'tiktokclone-f6937.firebaseapp.com',
    storageBucket: 'tiktokclone-f6937.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHQBuixMWkfxTu10Wh20k4ElddxHVUI5I',
    appId: '1:1002546867181:android:2534979f0729ea219c95e4',
    messagingSenderId: '1002546867181',
    projectId: 'tiktokclone-f6937',
    storageBucket: 'tiktokclone-f6937.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQX5gY5XwAgPUAPPqc0SU17Me_wuN7P6g',
    appId: '1:1002546867181:ios:8f18e65d920519b69c95e4',
    messagingSenderId: '1002546867181',
    projectId: 'tiktokclone-f6937',
    storageBucket: 'tiktokclone-f6937.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQX5gY5XwAgPUAPPqc0SU17Me_wuN7P6g',
    appId: '1:1002546867181:ios:1e68c054eaba4a219c95e4',
    messagingSenderId: '1002546867181',
    projectId: 'tiktokclone-f6937',
    storageBucket: 'tiktokclone-f6937.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
